---
title: "EcoAcc - Experiments"
author: "Kara Dobson"
date: 2024-11-12
format: html
editor: visual
---

## Ecological Acclimation: Warming Experiments

```{r, echo = F, message = F, warning = F}
# Load packages
library(tidyverse)
library(ggpubr)

# Set path to turbo to get data
path_data = "/nfs/turbo/seas-zhukai/proj-ecoacc/TeRaCON/"
setwd(path_data)
# Load in data
CTI_sens_teracon <- read.csv(" CTI_sens_teracon.csv")
NPP_teracon <- read.csv(" eco_response_teracon.csv")
# Set path to turbo to get data
path_data = "/nfs/turbo/seas-zhukai/proj-ecoacc/JRGCE/"
setwd(path_data)
# Load in data
CTI_sens_jrgce <- read.csv(" CTI_sens_jrgce.csv")
NPP_jrgce <- read.csv(" eco_response_jrgce.csv")
```

Using community composition and ecosystem response data from various warming experiments, we can visualize changes in community structure (e.g., CTI) alongside changes in function (e.g., ANPP). Including ambient temperatures changes over the course of each experiment may also inform the observed responses.

```{r, message = F, warning = F, fig.width = 10, fig.height = 6}
# CTI figures
CTI_tera_plot <- ggplot(CTI_sens_teracon, aes(x = year, y = sensitivity)) +
  geom_smooth() +
  labs(x = "Year", y = "CTI (Warmed - Ambient)") +
  scale_x_continuous(breaks = seq(2012, 2023, by = 2)) +
  theme_bw()
CTI_jrgce_plot <- ggplot(CTI_sens_jrgce, aes(x = year, y = sensitivity)) +
  geom_smooth() +
  labs(x = "Year", y = "CTI (Warmed - Ambient)") +
  scale_x_continuous(breaks = seq(1998, 2014, by = 2)) +
  theme_bw()

# Biomass figures
NPP_teracon <- NPP_teracon %>%
  filter(variable == "mean_ab_bio")
npp_tera_plot <- ggplot(NPP_teracon, aes(x = year, y = sensitivity)) +
  geom_smooth() +
  labs(x = "Year", y = "Biomass (Warmed - Ambient)") +
  scale_x_continuous(breaks = seq(2012, 2023, by = 2)) +
  theme_bw()
npp_jrgce_plot <- ggplot(NPP_jrgce, aes(x = year, y = sensitivity)) +
  geom_smooth() +
  labs(x = "Year", y = "Biomass (Warmed - Ambient)") +
  scale_x_continuous(breaks = seq(1998, 2014, by = 2)) +
  theme_bw()

# Ambient temp change figures
temp_tera_plot <- ggplot(CTI_sens_teracon, aes(x = year, y = mean_C_temp_summer)) +
  geom_smooth() +
  labs(x = "Year", y = "Ambient temperature (°C)") +
  scale_x_continuous(breaks = seq(2012, 2023, by = 2)) +
  theme_bw()
temp_jrgce_plot <- ggplot(CTI_sens_jrgce, aes(x = year, y = mean_C_temp_summer)) +
  geom_smooth() +
  labs(x = "Year", y = "Ambient temperature (°C)") +
  scale_x_continuous(breaks = seq(1998, 2014, by = 2)) +
  theme_bw()

# Combine figures into one multi-panel plot
ggarrange(CTI_tera_plot,npp_tera_plot,temp_tera_plot,
          CTI_jrgce_plot,npp_jrgce_plot,temp_jrgce_plot,
          ncol = 3, nrow=2, common.legend = T, legend = "right")
```
